Hamburger 컴포넌트 추가
Da-ily/Da-ily pull request #95
Opened 2023-12-31 09:19 UTC by hangooksaram

## 연관 이슈
close: #91
## 작업 내용
* Hamburger 컴포넌트 추가
   - anchor props : 클릭시 햄버거 메뉴의 위치 결정
* 아이콘 에셋 추가
   - hamburger-more-icon.svg, download-icon.svg 추가
## 의논할 거리
## Merge 전에 해야할 작업
## 기타

2023-12-31 09:48 UTC, puranium235 requested changes
주말인데 고생하셨습니다! 연말 잘 보내시고 새해 복 많이받으세요~

2023-12-31 09:48 UTC, puranium235 commented on frontend/src/components/common/Hamburger/Hamburger.styled.jsx
> +  animation: ${fadeIn} 0.3s;
여기도 display 속성 먼저 나열하고, 한줄 띄고 크기와 padding, margin 쓰고 하는식으로 해주시면 읽기 편할 것 같아요! 컨벤션 문서에 대략적인 순서가 있어요.

2023-12-31 09:48 UTC, puranium235 commented on frontend/src/components/common/Hamburger/Hamburger.jsx
> +} from './Hamburger.styled';
`import * as S` 로 부탁드립니다!

2023-12-31 09:48 UTC, puranium235 commented on frontend/src/components/common/Hamburger/Hamburger.jsx
> +  const [isOpen, setIsOpen] = useState(false);
혹시 다른데를 클릭했을 때 햄버거메뉴가 닫힌다든지 이렇게도 넣을 수 있을까요?

2023-12-31 09:55 UTC, puranium235 commented
햄버거 스토리도 추가 부탁드립니다!

2023-12-31 13:50 UTC, hangooksaram commented on frontend/src/components/common/Hamburger/Hamburger.styled.jsx
> +  animation: ${fadeIn} 0.3s;
넵 알겠습니다! 조금 급하게 작업하다보니 전체적으로 놓친 부분이 많은 것 같네요. 문서 참고해서 수정하도록 하겠습니다!

2023-12-31 13:50 UTC, hangooksaram commented on frontend/src/components/common/Hamburger/Hamburger.jsx
> +} from './Hamburger.styled';
이것도 저번에 피드백 해주셨는데, 놓친것 같네요 ㅠㅠ 수정해두겠습니다.

2023-12-31 13:52 UTC, hangooksaram commented on frontend/src/components/common/Hamburger/Hamburger.jsx
> +  const [isOpen, setIsOpen] = useState(false);
현재 해당 액션 가능합니다!

```js
/** .. */
{isOpen && <Overlay onClick={() => setIsOpen(false)} />}
/** .. */
```

2023-12-31 13:55 UTC, hangooksaram commented
> 주말인데 고생하셨습니다! 연말 잘 보내시고 새해 복 많이받으세요~

감사합니다!! [puranium235](https://github.com/puranium235) 님도 새해복많이받으세요 ☺️

2023-12-31 15:39 UTC, puranium235 commented on frontend/src/components/common/Hamburger/Hamburger.jsx
> +  const [isOpen, setIsOpen] = useState(false);
아하! 제가 아까 이부분 이해를 못했었는데 전체에 오버레이를 깔고 이벤트를 넣어주신거군요! 설명 감사합니다~

2024-01-01 16:41 UTC, puranium235 approved these changes
고생하셨습니다!

2024-01-02 02:23 UTC, hangooksaram commented
> 햄버거 스토리도 추가 부탁드립니다!

햄버거 컴포넌트 에 svg 파일이 쓰이는데, storybook 에서 svg 관련 이슈가 발생했습니다. 해당 이슈를 새로 오픈하고 해결한 뒤에, storybook 에 추가하는 작업 하도록 하겠습니다!

2024-01-02 02:24 UTC, merged